import type { Metadata } from "next";
import "./globals.css";
import inject from "@stylexjs/dev-runtime";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (process.env.NODE_ENV !== "production") {
    inject({
      classNamePrefix: "x",
      dev: true,
      test: false,
      useRemForFontSize: false,
      styleResolution: "application-order",
    });
  }
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
