import type { Metadata } from "next";
import "./globals.css";
// import inject from "@stylexjs/dev-runtime";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// inject({
//   classNamePrefix: "x",
//   dev: true,
//   test: false,
//   useRemForFontSize: false,
//   styleResolution: "application-order",
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
